import { BarChart3, Database, FileWarning, RefreshCw } from "lucide-react";
import { getAtlasData } from "@/data/loaders";

export default function MethodologyPage() {
  const data = getAtlasData();

  return (
    <main className="content-page">
      <section className="page-hero">
        <div className="eyebrow"><BarChart3 size={13} /> Methodology</div>
        <h1>Scored public signals, visible source gaps.</h1>
        <p>{data.methodology.summary}</p>
      </section>

      <section className="method-grid">
        <article>
          <Database size={19} />
          <h2>Source tiers</h2>
          <p>Tier 1 official sources are required for displayed v1 metrics. Catalogue entries can exist before a layer is normalized, but they cannot be converted into numeric claims without a defensible mapping.</p>
        </article>
        <article>
          <BarChart3 size={19} />
          <h2>Readiness score</h2>
          <p>Scores combine measured provincial firm counts, national R&D performer context, and source coverage. The model is directional and intentionally conservative about unnormalized layers.</p>
        </article>
        <article>
          <FileWarning size={19} />
          <h2>Evidence gaps</h2>
          <p>Labour, export, procurement, broadband, and remote energy layers are shown only when source-backed. If a mapping is unfinished, the interface says “Not yet available” instead of filling a placeholder.</p>
        </article>
        <article>
          <RefreshCw size={19} />
          <h2>Update cadence</h2>
          <p>Static artifacts are regenerated by `pnpm data:refresh`, reviewed, committed, and served by Vercel. This keeps public data reproducible and easy to audit.</p>
        </article>
      </section>

      <section className="method-section">
        <h2>Mission taxonomy</h2>
        <div className="taxonomy-table">
          {data.missions.map((mission) => (
            <article key={mission.id}>
              <h3>{mission.name}</h3>
              <dl>
                <div><dt>NAICS</dt><dd>{mission.taxonomy.naics.join(", ")}</dd></div>
                <div><dt>Procurement keywords</dt><dd>{mission.taxonomy.procurementKeywords.join(", ")}</dd></div>
                <div><dt>DCB labels</dt><dd>{mission.taxonomy.dcbLabels.join(", ")}</dd></div>
              </dl>
            </article>
          ))}
        </div>
      </section>

      <section className="method-section">
        <h2>Caveats</h2>
        <ul className="caveat-list">
          {data.methodology.caveats.map((caveat) => (
            <li key={caveat}>{caveat}</li>
          ))}
        </ul>
      </section>
    </main>
  );
}
